name: Continuous Integration For AustraliaCash
on:
  push:
    branches:
      - dev
      - aux-dev
      - master
      - aux-master
  pull_request:
    branches:
      - dev
      - aux-dev
      - master
      - aux-master
env:
  SOURCE_ARTIFACT: source
jobs:
  create-source-distribution:
    name: Create Source Distribution
    runs-on: ubuntu-22.04
    env:
      ARTIFACT_DIR: source
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Required Packages
      run: |
        sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3 autoconf-archive
        sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev
        sudo apt-get install libboost-all-dev
        sudo apt-get install software-properties-common
        sudo apt-get install libdb5.3-dev libdb5.3++-dev
        sudo apt-get update
        sudo apt-get install libminiupnpc-dev
        sudo apt-get install libzmq3-dev
        sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
        sudo apt-get install libqrencode-dev
    - name: Create Distribution Tarball
      run: |
        ./autogen.sh
        ./configure
        make dist
    - name: Download Dependencies
      run: make -C depends download
    - name: Create Dependencies Tarball
      run: tar -czf depends.tar.gz depends
    - name: Prepare Files for Artifact
      run: |
        mkdir -p $ARTIFACT_DIR
        mv depends.tar.gz australiacash-*.tar.gz $ARTIFACT_DIR
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.SOURCE_ARTIFACT }}
        path: ${{ env.ARTIFACT_DIR }}
    - name: List Downloaded Files
      run: |
        ls -R source


  build-linux-22:
    name: Build for Linux 22
    needs: create-source-distribution
    runs-on: ubuntu-22.04
    env:
      ARTIFACT_DIR: linux-ubu22-binaries
      TEST_LOG_ARTIFACT_DIR: test-logs
    steps:
    - name: Getting Source
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.SOURCE_ARTIFACT }}
        path: ${{ env.ARTIFACT_DIR }}
    
    # Debugging: List files in source directory
    - name: Check source directory content
      run: ls -R source
    
    - name: Extract Archives
      run: |
        # Ensure the file exists before attempting to move it
        ls -la source
        mv source/australiacash-2.02.01.tar.gz .
        mv source/depends.tar.gz .
        tar -xzf depends.tar.gz
        tar -xzf australiacash-2.02.01.tar.gz --strip-components=1

    - name: Install Required Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-zmq
    - name: Build Dependencies
      run: make -C depends -j$(nproc)
      working-directory: ${{ env.SOURCE_ARTIFACT }}
    - name: Build Australiacash
      run: |
        ./configure --prefix=$(realpath depends/x86_64-pc-linux-gnu)
        make -j$(nproc)
      working-directory: ${{ env.SOURCE_ARTIFACT }}
    - name: Prepare Files for Artifact
      run: |
        mkdir -p $ARTIFACT_DIR
        mv $SOURCE_ARTIFACT/src/{australiacash-cli,australiacash-tx,australiacashd,qt/australiacash-qt} $ARTIFACT_DIR
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-ubu22-binaries
        path: ${{ env.ARTIFACT_DIR }}


# Additional jobs for Windows, macOS, and Linux 20 will follow the same pattern.
